name: Main
on:
  pull_request:
    branches: 
    - master
    - develop
    - main
    
env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Install and run Spectral CI
      uses: spectralops/spectral-github-action@v3
      with:
        spectral-dsn: ${{ env.SPECTRAL_DSN }}
        spectral-args: scan --fail-on-error --engines secrets,iac,oss --include-tags base,audit,iac,secrets
