name: Main
on:
  fork:
    branches:
    - master
    - develop
    - main
  push:
    branches:
    - master
    - develop
    - main  
  pull_request:
    branches: 
    - master
    - develop
    - main
    
env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install and run Spectral CI
      uses: spectralops/spectral-github-action@v3
      with:
        spectral-dsn: ${{ env.SPECTRAL_DSN }}
        spectral-args: scan --ok --engines secrets,iac,oss --include-tags base,audit,iac
